# Generated by Django 4.1.3 on 2023-04-06 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FinancialData',
            new_name='FinancialDataModel',
        ),
    ]
